In [7]:
import pandas as pd
Location = "California.csv"
df = pd.read_csv(Location)
df.head()

,GEOID,SUMLEV,STATE,COUNTY,CBSA,CSA,NECTA,CNECTA,NAME,POP100,HU100,POP100.2000,HU100.2000,P001001,P001001.2000
0,6001,50,6,1,41860,488,NaN,NaN,Alameda County,1510271,582549,1443741,540183,1510271,1443741
1,6003,50,6,3,99999,999,NaN,NaN,Alpine County,1175,1760,1208,1514,1175,1208
2,6005,50,6,5,99999,999,NaN,NaN,Amador County,38091,18032,35100,15035,38091,35100
3,6007,50,6,7,17020,999,NaN,NaN,Butte County,220000,95835,203171,85523,220000,203171
4,6009,50,6,9,99999,999,NaN,NaN,Calaveras County,45578,27925,40554,22946,45578,40554